### ISSUE TITLE
"Doesn't seem to be a 360 picture, skipping picture"

### ISSUE THREAD

**Issue by RileZugo** [plord12/360tools#2]
I'm trying to upload photos created with the Street View app but I get the error  `Donesn't seem to be a 360 picture, skipping picture` (yes, the typo is actually on the error lol) They seem to work fine with 360 image viewers, and there is location data attached to them.
I don't have a proper 360 camera and cannot buy one.  Any way to fix this issue?

**Comment by plord12** [comment]
The tool reads the xmp metadata ( "ProjectionType" ) to determing if the image is a 360 or not.  I suppose your image doesn't contain this.

Maybe attach the picture here and I can take a look ?

**Comment by RileZugo** [comment]
Hi! Thanks for the quick reply. For now I was able to upload it with an app called Panorra, though the blue circle seems to only show up when you zoom in a good amount, not sure if that's normal or not.

Here is the picture: https://drive.google.com/file/d/1PP8iiOjd1PnFOzNY3svKaDaFCVxO04Eu/view?usp=drivesdk

**Comment by plord12** [comment]
Thanks for the picture.  At first glance the metadata looks fine :

```
exiftool PANO_20231019_121312_2.jpg 
...
Projection Type                 : equirectangular
...
```

I'll dig some more a little later.

Thanks for reporting.

**Comment by plord12** [comment]
Added support for this alternative way of specifying 360 image.

**Comment by plord12** [comment]
Closing
